int _putchar(char c);
void print_alphabets(void);
void print_alphabets_x10(void);
void print_to_99(int n);
void print_times_table(int n);
int add(int, int);
void print_last_digit(int);
int _abs(int);
int _islower(int c);
int _isalpha(int);
int print_sign(int n);
